### ISSUE TITLE
workshop_deploy task doesn't seem to associate the elastic ip with the boltws-master

### ISSUE THREAD

**Issue by psreed** [puppetlabs-seteam/workshop_deploy#3]
I had to manually do the association when the task was waiting for the instance to become available, then rerun the task.

`Starting: Waiting up to 5 minutes until AWS instance becomes available... on 52.27.8.145
Finished: Waiting up to 5 minutes until AWS instance becomes available... with 1 failure in 310.29 sec
Finished: plan workshop_deploy in 333.46 sec
{
  "kind": "bolt/run-failure",
  "msg": "Plan aborted: wait_until_available failed on 1 nodes",
  "details": {
    "action": "wait_until_available",
    "object": null,
    "result_set": [
      {
        "node": "52.27.8.145",
        "target": "52.27.8.145",
        "type": null,
        "object": null,
        "status": "failure",
        "result": {
          "_error": {
            "kind": "puppetlabs.tasks/exception-error",
            "issue_code": "EXCEPTION",
            "msg": "Timed out waiting for target",
            "details": {
              "class": "Bolt::Executor::TimeoutError",
              "stack_trace": "/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.17.0/lib/bolt/executor.rb:320:in ``wait_until'\\n/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.17.0/lib/bolt/executor.rb:302:in ``block (3 levels) in wait_until_available'\\n/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.17.0/lib/bolt/executor.rb:218:in ``with_node_logging'\\n/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.17.0/lib/bolt/executor.rb:300:in ``block (2 levels) in wait_until_available'\\n/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.17.0/lib/bolt/executor.rb:82:in ``block (3 levels) in queue_execute'\\n/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in ``run_task'\\n/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in ``block (3 levels) in create_worker'\\n/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in ``loop'\\n/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in ``block (2 levels) in create_worker'\\n/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in ``catch'\\n/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in ``block in create_worker'\\n/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in ``block in create_with_logging_context'"
            }
          }
        }
      }
    ]
  }
}`

**Comment by psreed** [comment]
doh ... of course it was something as simple as a typo in my hiera config... "awskit", not "awsket"!
Maybe this can serve as a lesson to others having similar issues ;)
